name: Update README

on:
  schedule:
    - cron: '* * * * *' # Runs at midnight UTC every day
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update README
        run: |
          python -c "from datetime import datetime; readme_path = 'README.md'; current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S'); content_to_add = f'Last updated on {current_time}'; with open(readme_path, 'a') as file: file.write('\n' + content_to_add)"

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update README with current date and time'
          add: 'README.md'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'main' # Replace with your default branch if it's not 'main'

